### ISSUE TITLE
窗口拖动卡顿

### ISSUE THREAD

**Issue by H1DDENADM1N** [Stardawn0v0/PyQtScrcpy#1]
使用鼠标左键拖动窗口，窗口移动非常缓慢，会出现两个鼠标指针。我测试了打包发布版本和从源码运行，同样bug。如下图：

系统版本：`Windows10 LTSC21H2 19044.4529`

![拖动卡顿](https://github.com/Stardawn0v0/PyQtScrcpy/assets/65646535/90eb2c9b-52cb-400c-9dce-e148e28fd06a)

**Comment by H1DDENADM1N** [comment]
从源码运行有如下警告：

```powershell
📢 Tips: QFluentWidgets Pro is now released. Click https://qfluentwidgets.com/pages/pro to learn more about it.


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "c:\Users\user0\Documents\PyQtScrcpy\main.py", line 27, in <module>
    from mainWindow import Ui_Form
  File "c:\Users\user0\Documents\PyQtScrcpy\mainWindow.py", line 672, in <module>
    import res_rc
  File "c:\Users\user0\Documents\PyQtScrcpy\res_rc.py", line 6, in <module>
    from PySide6 import QtCore
  File "C:\Users\user0\AppData\Local\Programs\Python\Python312\Lib\site-packages\PySide6\__init__.py", line 124, in <module>
    _setupQtDirectories()
  File "C:\Users\user0\AppData\Local\Programs\Python\Python312\Lib\site-packages\PySide6\__init__.py", line 64, in _setupQtDirectories
    from shiboken6 import Shiboken
  File "C:\Users\user0\AppData\Local\Programs\Python\Python312\Lib\site-packages\shiboken6\__init__.py", line 27, in <module>
    from shiboken6.Shiboken import *
Unknown property text-antialiasing
Unknown property text-antialiasing
C:\Users\user0\AppData\Local\Programs\Python\Python312\Lib\site-packages\qframelesswindow\windows\window_effect.py:100: UserWarning: The mica effect is only available on Win11
  warnings.warn("The mica effect is only available on Win11")
```

**Comment by Stardawn0v0** [comment]
因为我的运行环境是Win11所以没有对Win10做窗口背景特效的适配，下个版本会加上，感谢反馈

**Comment by Stardawn0v0** [comment]
刚刚的Commit尝试修复了这个问题，请问是否良好工作？如果不的话我就要去研究[PyQt-Frameless-Window](https://github.com/zhiyiYo/PyQt-Frameless-Window)了

**Comment by H1DDENADM1N** [comment]
> 刚刚的Commit尝试修复了这个问题，请问是否良好工作？如果不的话我就要去研究[PyQt-Frameless-Window](https://github.com/zhiyiYo/PyQt-Frameless-Window)了

未能良好工作，仍然卡顿：

![recording](https://github.com/user-attachments/assets/8b0797d9-bb0f-4586-a391-c24c2f6ef9dc)

**Comment by H1DDENADM1N** [comment]
补充：

运行PyQt-Frameless-Window的示例是不卡的：

![recording](https://github.com/user-attachments/assets/4d7105c1-83c6-4231-8662-b6f2652eed8b)

**Comment by Stardawn0v0** [comment]
你运行的是不带特效的Demo，当然不会卡
似乎只能在Windows10上禁用窗口模糊特效来解决这个问题了

**Comment by Stardawn0v0** [comment]
现在在Win10上不会使用AcrylicWindow了
