### ISSUE TITLE
Redmi note 12 5G无法使用

### ISSUE THREAD

**Issue by zixipurple** [Stardawn0v0/PyQtScrcpy#4]
红米K40使用一切正常，但是换到红米 note 12 5G后
CMD疯狂提示以下内容，且有图像无法控制屏幕
设备系统：安卓14 澎湃OS1.0.2.0.UMQCNXM
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:230)
        at com.genymobile.scrcpy.Device.injectEvent(Device.java:234)
        at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:362)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:162)
        at com.genymobile.scrcpy.Controller.control(Controller.java:97)
        at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:105)
        at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
        at android.os.Parcel.createException(Parcel.java:3041)
        at android.os.Parcel.readException(Parcel.java:3024)
        at android.os.Parcel.readException(Parcel.java:2966)
        at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
        at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
        at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
        ... 10 more

**Comment by Stardawn0v0** [comment]
米系设备貌似都有这个问题，是小米限制adb input造成的，重新开关USB调试（安全设置）不行的话我也没有太好的方法，有空可以更新一下内置scrcpy版本试试



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月26日 18:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [Stardawn0v0/PyQtScrcpy] Redmi note 12 5G无法使用 (Issue #4) |

红米K40使用一切正常，但是换到红米 note 12 5G后
CMD疯狂提示以下内容，且有图像无法控制屏幕
设备系统：安卓14 澎湃OS1.0.2.0.UMQCNXM
[server] ERROR: Could not invoke method
java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.genymobile.scrcpy.wrappers.InputManager.injectInputEvent(InputManager.java:58)
at com.genymobile.scrcpy.Device.injectEvent(Device.java:230)
at com.genymobile.scrcpy.Device.injectEvent(Device.java:234)
at com.genymobile.scrcpy.Controller.injectTouch(Controller.java:362)
at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:162)
at com.genymobile.scrcpy.Controller.control(Controller.java:97)
at com.genymobile.scrcpy.Controller.lambda$start$0$com-genymobile-scrcpy-Controller(Controller.java:105)
at com.genymobile.scrcpy.Controller$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.SecurityException: Injecting input events requires the caller (or the source of the instrumentation, if any) to have the INJECT_EVENTS permission.
at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
at android.os.Parcel.createException(Parcel.java:3041)
at android.os.Parcel.readException(Parcel.java:3024)
at android.os.Parcel.readException(Parcel.java:2966)
at android.hardware.input.IInputManager$Stub$Proxy.injectInputEventToTarget(IInputManager.java:1590)
at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1217)
at android.hardware.input.InputManagerGlobal.injectInputEvent(InputManagerGlobal.java:1227)
... 10 more

**Comment by Stardawn0v0** [comment]
在开始投屏前会检查`persist.security.adbinput`的状态，未启用时会进行提示，应该可以一定程度上避免这种情况
